### ISSUE TITLE
ImportError: cannot import name 'StreamWrapper' from 'torch.utils.data.datapipes.utils.common'

### ISSUE THREAD

**Issue by d4l3k** [pytorch/data#108]
## 🐛 Bug

Seems like there's some messed up import paths? some things are torch.data where as others are torchdata?

```
(3.7.11) tristanr@tristanr-arch2 ~> pip install -e git+https://github.com/pytorch/data#egg=torchdata
Obtaining torchdata from git+https://github.com/pytorch/data#egg=torchdata
  Cloning https://github.com/pytorch/data to ./venvs/3.7.11/src/torchdata
  Running command git clone --filter=blob:none -q https://github.com/pytorch/data /home/tristanr/venvs/3.7.11/src/torchdata
  Resolved https://github.com/pytorch/data to commit 2d94ebc6e95d4bd475a98e947781e58410386a10
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests in ./venvs/3.7.11/lib/python3.7/site-packages (from torchdata) (2.26.0)
Requirement already satisfied: torch in ./venvs/3.7.11/lib/python3.7/site-packages (from torchdata) (1.10.0)
Requirement already satisfied: certifi>=2017.4.17 in ./venvs/3.7.11/lib/python3.7/site-packages (from requests->torchdata) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in ./venvs/3.7.11/lib/python3.7/site-packages (from requests->torchdata) (2.0.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./venvs/3.7.11/lib/python3.7/site-packages (from requests->torchdata) (1.26.7)
Requirement already satisfied: idna<4,>=2.5 in ./venvs/3.7.11/lib/python3.7/site-packages (from requests->torchdata) (3.3)
Requirement already satisfied: typing-extensions in ./venvs/3.7.11/lib/python3.7/site-packages (from torch->torchdata) (3.10.0.2)
Installing collected packages: torchdata
  Attempting uninstall: torchdata
    Found existing installation: torchdata 0.2.0
    Uninstalling torchdata-0.2.0:
      Successfully uninstalled torchdata-0.2.0
  Running setup.py develop for torchdata
Successfully installed torchdata-0.1.0a0+2d94ebc
(3.7.11) tristanr@tristanr-arch2 ~> python -c "import torchdata"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tristanr/venvs/3.7.11/src/torchdata/torchdata/__init__.py", line 2, in <module>
    from . import datapipes
  File "/home/tristanr/venvs/3.7.11/src/torchdata/torchdata/datapipes/__init__.py", line 3, in <module>
    from . import iter
  File "/home/tristanr/venvs/3.7.11/src/torchdata/torchdata/datapipes/iter/__init__.py", line 24, in <module>
    from torchdata.datapipes.iter.load.online import (
  File "/home/tristanr/venvs/3.7.11/src/torchdata/torchdata/datapipes/iter/load/online.py", line 10, in <module>
    from torchdata.datapipes.utils import StreamWrapper
  File "/home/tristanr/venvs/3.7.11/src/torchdata/torchdata/datapipes/utils/__init__.py", line 2, in <module>
    from torch.utils.data.datapipes.utils.common import StreamWrapper
ImportError: cannot import name 'StreamWrapper' from 'torch.utils.data.datapipes.utils.common' (/home/tristanr/venvs/3.7.11/lib/python3.7/site-packages/torch/utils/data/datapipes/utils/common.py)
```

## To Reproduce

1. `pip install -e git+https://github.com/pytorch/data#egg=torchdata`
1. `python -c "import torchdata"`

## Expected behavior

No import error

## Environment

```
PyTorch version: 1.10.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 11.1.0
Clang version: Could not collect
CMake version: version 3.22.0
Libc version: glibc-2.33

Python version: 3.7.11 (default, Nov 22 2021, 11:26:35)  [GCC 11.1.0] (64-bit runtime)
Python platform: Linux-5.14.16-arch1-1-x86_64-with-arch
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] botorch==0.5.1
[pip3] gpytorch==1.5.1
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.4
[pip3] torch==1.10.0
[pip3] torchdata==0.1.0a0+2d94ebc
[pip3] torchmetrics==0.6.0
[pip3] torchvision==0.11.1
[pip3] torchx==0.1.2.dev0
[conda] blas                      1.0                         mkl  
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-include               2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] mypy_extensions           0.4.3            py39h06a4308_0  
[conda] numpy                     1.20.3           py39hf144106_0  
[conda] numpy-base                1.20.3           py39h74d4b33_0  
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
```

**Comment by ejguan** [comment]
Yeah, unfortunately as TorchData is not official release yet, you have to use PyTorch nightly with TorchData. The `StreamWrapper` didn't get into PT 1.10 release.

**Comment by d4l3k** [comment]
@ejguan got it, thanks!

```
pip install --pre torch torchvision torchtext torchaudio -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html --upgrade
```
solved that for me
