### ISSUE TITLE
Exception in main process not properly propagating when having more than one worker and using `torch.Tensor` (MPRS)

### ISSUE THREAD

**Issue by sehoffmann** [pytorch/data#1103]
### 🐛 Describe the bug

Code to reproduce:
```
import torch
import time
import random
from torchdata.datapipes.iter import IterableWrapper
from torchdata.dataloader2 import DataLoader2, MultiProcessingReadingService

def raise_exception(x):
    raise RuntimeError('test')

def rand_sleep(x):
    time.sleep(random.random()*0.2)
    return x

pipe = IterableWrapper([torch.rand(1) for _ in range(100)])
pipe = pipe.map(rand_sleep)
pipe = pipe.non_replicable().map(raise_exception)
dl = DataLoader2(pipe, reading_service=MultiProcessingReadingService(4))
try:
    list(dl)
except RuntimeError as e:
    print('Catched: ', e)
```

Output:
```Traceback (most recent call last):
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/dataloader2.py", line 55, in __next__
    next_val = next(self.dataloader._datapipe_iter)  # type: ignore[arg-type]
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 173, in wrap_generator
    response = gen.send(None)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/site-packages/torch/utils/data/datapipes/iter/callable.py", line 123, in __iter__
    yield self._apply_fn(data)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/site-packages/torch/utils/data/datapipes/iter/callable.py", line 88, in _apply_fn
    return self.fn(data)
  File "/mnt/qb/work2/goswami0/gkd021/atmodata/examples/weatherbench.py", line 63, in raise_exception
    raise RuntimeError('test')
RuntimeError: test
This exception is thrown by __iter__ of MapperIterDataPipe(datapipe=NonReplicableIterDataPipe, fn=raise_exception, input_col=None, output_col=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/qb/work2/goswami0/gkd021/atmodata/examples/weatherbench.py", line 75, in <module>
    list(dl)
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/dataloader2.py", line 67, in __next__
    self.dataloader.shutdown()
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/dataloader2.py", line 256, in shutdown
    self.reading_service.finalize()
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/reading_service.py", line 357, in finalize
    clean_me(process, req_queue, res_queue)
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/reading_service.py", line 349, in clean_me
    _ = res_queue.get(timeout=default_dl2_worker_join_timeout_in_s)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
```

I believe this only happens when transmitting `torch.Tensor`s since the error goes away as soon as I switch to ints. If we comment out the sleep we instead get this exception:
```
Traceback (most recent call last):
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/dataloader2.py", line 55, in __next__
    next_val = next(self.dataloader._datapipe_iter)  # type: ignore[arg-type]
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 173, in wrap_generator
    response = gen.send(None)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/site-packages/torch/utils/data/datapipes/iter/callable.py", line 123, in __iter__
    yield self._apply_fn(data)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/site-packages/torch/utils/data/datapipes/iter/callable.py", line 88, in _apply_fn
    return self.fn(data)
  File "/mnt/qb/work2/goswami0/gkd021/atmodata/examples/weatherbench.py", line 63, in raise_exception
    raise RuntimeError('test')
RuntimeError: test
This exception is thrown by __iter__ of MapperIterDataPipe(datapipe=NonReplicableIterDataPipe, fn=raise_exception, input_col=None, output_col=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/qb/work2/goswami0/gkd021/atmodata/examples/weatherbench.py", line 75, in <module>
    list(dl)
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/dataloader2.py", line 67, in __next__
    self.dataloader.shutdown()
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/dataloader2.py", line 256, in shutdown
    self.reading_service.finalize()
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/reading_service.py", line 357, in finalize
    clean_me(process, req_queue, res_queue)
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/reading_service.py", line 349, in clean_me
    _ = res_queue.get(timeout=default_dl2_worker_join_timeout_in_s)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/connection.py", line 509, in Client
    deliver_challenge(c, authkey)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/connection.py", line 740, in deliver_challenge
    response = connection.recv_bytes(256)        # reject large message
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
```

In my production code, I get even more contrived errors. Here, one key difference might be that I'm creating the `torch.Tensor`s in the worker processes, not in the main process. I'm also using a `sharding_round_robin_dispatch`. The exception that causes this is a runtime error thrown because I'm trying to transfer tensors to gpu even though im running on a cpu-only machine. This exception is raised at the same place as in the example code above:
```
Traceback (most recent call last):
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/dataloader2.py", line 55, in __next__
    next_val = next(self.dataloader._datapipe_iter)  # type: ignore[arg-type]
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 173, in wrap_generator
    response = gen.send(None)
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/datapipes/iter/util/prefetcher.py", line 100, in __iter__
    raise data
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/datapipes/iter/util/prefetcher.py", line 71, in thread_worker
    item = next(itr)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 173, in wrap_generator
    response = gen.send(None)
  File "/mnt/qb/work2/goswami0/gkd021/atmodata/atmodata/iter/tensor.py", line 49, in __iter__
    for batches in zip(*([it] * self.n_interleaves)):
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 173, in wrap_generator
    response = gen.send(None)
  File "/mnt/qb/work2/goswami0/gkd021/atmodata/atmodata/iter/tensor.py", line 64, in __iter__
    yield x.to(self.device, non_blocking=self.non_blocking)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/site-packages/torch/cuda/__init__.py", line 256, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
This exception is thrown by __iter__ of ThToDevice(device='cuda', dp=NonReplicableIterDataPipe, non_blocking=False)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/qb/work2/goswami0/gkd021/atmodata/examples/weatherbench.py", line 53, in <module>
    main()
  File "/mnt/qb/work2/goswami0/gkd021/atmodata/examples/weatherbench.py", line 49, in main
    benchmark(dl)
  File "/mnt/qb/work2/goswami0/gkd021/atmodata/atmodata/utils.py", line 9, in benchmark
    batch = next(it)
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/dataloader2.py", line 67, in __next__
    self.dataloader.shutdown()
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/dataloader2.py", line 256, in shutdown
    self.reading_service.finalize()
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/reading_service.py", line 357, in finalize
    clean_me(process, req_queue, res_queue)
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/reading_service.py", line 349, in clean_me
    _ = res_queue.get(timeout=default_dl2_worker_join_timeout_in_s)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <function DataLoader2.__del__ at 0x7f446b936ef0>
Traceback (most recent call last):
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/dataloader2.py", line 243, in __del__
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/dataloader2.py", line 256, in shutdown
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/reading_service.py", line 357, in finalize
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/reading_service.py", line 349, in clean_me
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/queues.py", line 122, in get
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReadingServiceInterface.__del__ at 0x7f446b935b40>
Traceback (most recent call last):
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/reading_service.py", line 102, in __del__
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/reading_service.py", line 357, in finalize
  File "/Traceback (most recent call last):
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/dataloader2.py", line 55, in __next__
    next_val = next(self.dataloader._datapipe_iter)  # type: ignore[arg-type]
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 173, in wrap_generator
    response = gen.send(None)
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/datapipes/iter/util/prefetcher.py", line 100, in __iter__
    raise data
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/datapipes/iter/util/prefetcher.py", line 71, in thread_worker
    item = next(itr)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 173, in wrap_generator
    response = gen.send(None)
  File "/mnt/qb/work2/goswami0/gkd021/atmodata/atmodata/iter/tensor.py", line 49, in __iter__
    for batches in zip(*([it] * self.n_interleaves)):
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 173, in wrap_generator
    response = gen.send(None)
  File "/mnt/qb/work2/goswami0/gkd021/atmodata/atmodata/iter/tensor.py", line 64, in __iter__
    yield x.to(self.device, non_blocking=self.non_blocking)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/site-packages/torch/cuda/__init__.py", line 256, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
This exception is thrown by __iter__ of ThToDevice(device='cuda', dp=NonReplicableIterDataPipe, non_blocking=False)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/qb/work2/goswami0/gkd021/atmodata/examples/weatherbench.py", line 53, in <module>
    main()
  File "/mnt/qb/work2/goswami0/gkd021/atmodata/examples/weatherbench.py", line 49, in main
    benchmark(dl)
  File "/mnt/qb/work2/goswami0/gkd021/atmodata/atmodata/utils.py", line 9, in benchmark
    batch = next(it)
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/dataloader2.py", line 67, in __next__
    self.dataloader.shutdown()
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/dataloader2.py", line 256, in shutdown
    self.reading_service.finalize()
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/reading_service.py", line 357, in finalize
    clean_me(process, req_queue, res_queue)
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/reading_service.py", line 349, in clean_me
    _ = res_queue.get(timeout=default_dl2_worker_join_timeout_in_s)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <function DataLoader2.__del__ at 0x7f446b936ef0>
Traceback (most recent call last):
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/dataloader2.py", line 243, in __del__
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/dataloader2.py", line 256, in shutdown
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/reading_service.py", line 357, in finalize
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/reading_service.py", line 349, in clean_me
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/queues.py", line 122, in get
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReadingServiceInterface.__del__ at 0x7f446b935b40>
Traceback (most recent call last):
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/reading_service.py", line 102, in __del__
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/reading_service.py", line 357, in finalize
  File "/mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/reading_service.py", line 349, in clean_me
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/queues.py", line 122, in get
ImportError: sys.meta_path is None, Python is likely shutting down
mnt/qb/work2/goswami0/gkd021/torchdata/torchdata/dataloader2/reading_service.py", line 349, in clean_me
  File "/mnt/qb/work2/goswami0/gkd021/conda/envs/wb/lib/python3.10/multiprocessing/queues.py", line 122, in get
ImportError: sys.meta_path is None, Python is likely shutting down
```

### Versions

```
[pip3] numpy==1.23.5
[pip3] numpy-groupies==0.9.20
[pip3] pytorch-triton==2.1.0+2c32f43999
[pip3] torch==2.1.0.dev20230314+cu117
[pip3] torchaudio==2.0.0.dev20230314+cu117
[pip3] torchdata==0.7.0a0+f1283eb
[pip3] torchvision==0.15.0.dev20230314+cu117
[conda] blas                      2.116                       mkl    conda-forge
[conda] blas-devel                3.9.0            16_linux64_mkl    conda-forge
[conda] cudatoolkit               11.7.0              hd8887f6_10    nvidia
[conda] libblas                   3.9.0            16_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            16_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            16_linux64_mkl    conda-forge
[conda] liblapacke                3.9.0            16_linux64_mkl    conda-forge
[conda] mkl                       2022.1.0           h84fe81f_915    conda-forge
[conda] mkl-devel                 2022.1.0           ha770c72_916    conda-forge
[conda] mkl-include               2022.1.0           h84fe81f_915    conda-forge
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] numpy-groupies            0.9.20                   pypi_0    pypi
[conda] numpy_groupies            0.9.20             pyhd8ed1ab_0    conda-forge
[conda] pytorch                   1.13.1          py3.10_cuda11.7_cudnn8.5.0_0    pytorch
[conda] pytorch-cuda              11.7                 h67b0de4_1    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-triton            2.1.0+2c32f43999          pypi_0    pypi
[conda] torch                     2.1.0.dev20230314+cu117          pypi_0    pypi
[conda] torchaudio                2.0.0.dev20230314+cu117          pypi_0    pypi
[conda] torchdata                 0.7.0a0+f1283eb          pypi_0    pypi
[conda] torchvision               0.15.0.dev20230314+cu117          pypi_0    pypi

```

**Comment by ejguan** [comment]
Could you pls try to PyTorch and TorchData nightly? I think my PR #1096 might have solved the problem to properly exit worker processes.

We might do a minor release in the coming months to adopt this patch

**Comment by ejguan** [comment]
You can find how to install pytorch nightly via https://pytorch.org/get-started/locally/
