### ISSUE TITLE
torchdata.datapipes.map.Shuffler should return a MapDataPipe not IterDataPipe

### ISSUE THREAD

**Issue by quancs** [pytorch/data#1132]
### 🐛 Describe the bug

I am working on mixing two speech datasets, both of them are indexable datasets. Using MapDataPipe, shuffle one of the speech datasets, and zip them together with one zipper:

```python
import torchdata.datapipes as dp

dp1 = dp.map.SequenceWrapper([0, 1, 2, 3, 4, 5]) # speech 1
dp2 = dp.map.SequenceWrapper(['a', 'b', 'c']) # speech 2
dp1 = dp.map.Shuffler(dp1) # shuffle one
dpz = dp.map.Zipper(dp1, dp2)

print(list(dpz))
print(list(dpz))
print(list(dpz))
print()
```
However, the shuffler returns one IterDataPipe... So the code above raises an Exception:
```
Traceback (most recent call last):
  File "/mnt/home/quancs/projects/NBSS_pmt/testxxx.py", line 6, in <module>
    dpz = dp.map.Zipper(dp1, dp2)
  File "/mnt/home/quancs/miniconda3/envs/torch2/lib/python3.10/site-packages/torch/utils/data/datapipes/map/combining.py", line 80, in __init__
    raise TypeError("Expected all inputs to be `MapDataPipe`")
TypeError: Expected all inputs to be `MapDataPipe`
```

I tried to use IterDataPipe, but I don't know how to sample it in ddp situation (in one epoch, each sample is sampled only once).

### Versions

Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
Clang version: Could not collect
CMake version: version 2.8.12.2
Libc version: glibc-2.17

Python version: 3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.3.109
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 530.30.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                128
On-line CPU(s) list:   0-127
Thread(s) per core:    1
Core(s) per socket:    64
Socket(s):             2
NUMA node(s):          8
Vendor ID:             AuthenticAMD
CPU family:            23
Model:                 49
Model name:            AMD EPYC 7742 64-Core Processor
Stepping:              0
CPU MHz:               1500.000
CPU max MHz:           2250.0000
CPU min MHz:           1500.0000
BogoMIPS:              4491.63
Virtualization:        AMD-V
L1d cache:             32K
L1i cache:             32K
L2 cache:              512K
L3 cache:              16384K
NUMA node0 CPU(s):     0-15
NUMA node1 CPU(s):     16-31
NUMA node2 CPU(s):     32-47
NUMA node3 CPU(s):     48-63
NUMA node4 CPU(s):     64-79
NUMA node5 CPU(s):     80-95
NUMA node6 CPU(s):     96-111
NUMA node7 CPU(s):     112-127
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc art rep_good nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 cpb cat_l3 cdp_l3 hw_pstate sme retpoline_amd ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip overflow_recov succor smca

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==2.0.1.post0
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.0
[pip3] torchdata==0.6.0
[pip3] torcheval==0.0.6
[pip3] torchmetrics==0.11.4
[pip3] torchtnt==0.0.7
[pip3] torchvision==0.15.0
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0           py310h7f8727e_0  
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0  
[conda] mkl_random                1.2.2           py310h00e6091_0  
[conda] numpy                     1.23.5          py310hd5efca6_0  
[conda] numpy-base                1.23.5          py310h8e6c178_0  
[conda] pytorch                   2.0.0           py3.10_cuda11.8_cudnn8.7.0_0    pytorch
[conda] pytorch-cuda              11.8                 h7e8668a_3    pytorch
[conda] pytorch-lightning         2.0.1.post0              pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.0.0               py310_cu118    pytorch
[conda] torchdata                 0.6.0                    pypi_0    pypi
[conda] torcheval                 0.0.6                    pypi_0    pypi
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchtnt                  0.0.7                    pypi_0    pypi
[conda] torchtriton               2.0.0                     py310    pytorch
[conda] torchvision               0.15.0              py310_cu118    pytorch

**Comment by NivekT** [comment]
Hi,

We intentionally made this change in release 0.5.0 ([release note](https://github.com/pytorch/data/releases/tag/v0.5.0)) and more discussion can be found here: https://github.com/pytorch/pytorch/pull/83202

We are happy to discuss any other use case further to see if we can improve our API.

**Comment by quancs** [comment]
@NivekT I just think it's wired to return a IterDataPipe after shuflling a MapDataPipe. I think it's a better choice to make Shuffler return a MapDataPipe which returns a tuple `(original index, data corresponding to the original index)` given a shuflled index.

**Comment by quancs** [comment]
For my situation, the current API is OK if I can use IterDataPipe to easily achieve that in one epoch, each sample is sampled only once with ddp used. I know it's easy to achieve that for a MapDataPipe by using DistributedSampler.
> I tried to use IterDataPipe, but I don't know how to sample it in ddp situation (in one epoch, each sample is sampled only once).

**Comment by ejguan** [comment]
@quancs There is no `Sampler` concept anymore in `TorchData` and that's one of the reasons that we convert `MapDataPipe.shuffle` to `IterDataPipe`. And, it's not intuitive for me that `MapDataPipe` has an order because it's intentionally for the random-access pattern rather than sequential access pattern

**Comment by quancs** [comment]
@ejguan Could you tell me how to sample each sample only once in one epoch with ddp used if I use IterDataPipe in my case?
