### ISSUE TITLE
Returning tensor instead of dict for state_dict causes failure

### ISSUE THREAD

**Issue by gokulavasan** [pytorch/data#1271]
### 🐛 Describe the bug

```
class TensorStateDataset(torch.utils.data.IterableDataset, Stateful, Iterator):
    def __init__(self, length):
        self.length = length
        self.i = 0

    def __iter__(self):
        return self
    
    def __next__(self):
        if self.i >= self.length:
            raise StopIteration
        self.i += 1
        return self.i

    def state_dict(self):
        return torch.rand(2, 2)

    def load_state_dict(self, state_dict):
		pass


class TestSimple(TestCase):
    def test(self):
        dataset = TensorStateDataset(100)
        dl = StatefulDataLoader(
            dataset=dataset,
            num_workers=1,
        )
        it = iter(dl)
        for _ in range(30):
            next(it)
        self.assertTrue(False)
```

Running this, I hit an error as follows:

```

self = <torch._utils.ExceptionWrapper object at 0x7f921c5fde10>

    def reraise(self):
        r"""Reraises the wrapped exception in the current thread"""
        # Format a message such as: "Caught ValueError in DataLoader worker
        # process 2. Original Traceback:", followed by the traceback.
        msg = f"Caught {self.exc_type.__name__} {self.where}.\nOriginal {self.exc_msg}"
        if self.exc_type == KeyError:
            # KeyError calls repr() on its argument (usually a dict key). This
            # makes stack traces unreadable. It will not be changed in Python
            # (https://bugs.python.org/issue2651), so we work around it.
            msg = KeyErrorMessage(msg)
        elif getattr(self.exc_type, "message", None):
            # Some exceptions have first argument as non-str but explicitly
            # have message field
            raise self.exc_type(message=msg)
        try:
            exception = self.exc_type(msg)
        except TypeError:
            # If the exception takes multiple arguments, don't try to
            # instantiate since we don't know how to
            raise RuntimeError(msg) from None
>       raise exception
E       RuntimeError: Caught RuntimeError in DataLoader worker process 0.
E       Original Traceback (most recent call last):
E         File "/home/gokulg/torchdata/data/torchdata/stateful_dataloader/worker.py", line 233, in _worker_loop
E           delta_state_dict = incremental_worker_state.generate_delta(state_dict)
E         File "/home/gokulg/torchdata/data/torchdata/stateful_dataloader/incremental_state.py", line 142, in generate_delta
E           if iter_state := fetcher_state.get(_DATASET_ITER_STATE, None):
E       RuntimeError: Boolean value of Tensor with more than one value is ambiguous
E
E
E       To execute this test, run the following from the base repo dir:
E            python test/stateful_dataloader/test_state_dict.py -k test2
E
E       This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

../../.conda/envs/basetorch/lib/python3.10/site-packages/torch/_utils.py:722: RuntimeError
```

If an integer is returned or say dict (with value as tensor) is returned, there is no error. 

### Versions

Latest git commit 82918dd

**Comment by andrewkho** [comment]
@gokulavasan we should probably try and fix this before release-branch cut, would this be straightforward?

**Comment by gokulavasan** [comment]
Fix is in this PR - https://github.com/pytorch/data/pull/1272
