### ISSUE TITLE
Maximum recursion depth exceeded when creating a DataLoader for an IterDataPipe dataset

### ISSUE THREAD

**Issue by tangbinh** [pytorch/data#149]
### 🐛 Describe the bug

It looks like there's an infinite loop involving the [`traverse`](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/graph.py#L57-L65) function when we try to instantiate a data loader from the following dataset. 

```python
import os
from torchdata.datapipes.iter import HttpReader, IterableWrapper, FileLoader
from torch.utils.data import IterDataPipe
from torch.utils.data.dataloader import DataLoader


MD5 = "9f81648d4199384278b86e315dac217c"
URL = "https://dl.fbaipublicfiles.com/glue/data/SST-2.zip"


class SST2Dataset(IterDataPipe):
    """The SST2 dataset uses torchdata datapipes end-2-end.
    To avoid download at every epoch, we cache the data on-disk
    We do sanity check on dowloaded and extracted data
    """

    def __init__(self, root, split, validate_hash=True):
        self._dp = self._get_datapipe(root, split, validate_hash)

    def __iter__(self):
        for data in self._dp:
            yield data

    def _get_datapipe(self, root, split, validate_hash):
        # Validate integrity of dataset using md5 checksum
        hash_dict = {os.path.join(root, "SST-2.zip"): MD5} if validate_hash else None
        hash_type = "md5" if validate_hash else None

        # cache data on-disk
        cache_dp = IterableWrapper([URL]).on_disk_cache(
            filepath_fn=lambda x: os.path.join(root, os.path.basename(x)),
            hash_dict=hash_dict,
            hash_type=hash_type,
        )
        cache_dp = HttpReader(cache_dp).end_caching(mode="wb", same_filepath_fn=True)

        # Load from cached file
        cache_dp = FileLoader(cache_dp, mode="rb")
        # extract data from zip
        extracted_files = cache_dp.read_from_zip().filter(
            lambda x: f"{split}.tsv" in x[0]
        )
        parsed_data = extracted_files.parse_csv(skip_lines=1, delimiter="\t").map(
            lambda x: (x[0], x[1])
        )
        return parsed_data


dataset = SST2Dataset(root=".", split="train", validate_hash=True)
dataloader = DataLoader(dataset, batch_size=None, shuffle=False)
print(next(iter(dataloader)))
```

Here's the stacktrace:
```
Traceback (most recent call last):
  File "/data/home/binhtang/repos/scratch/fun.py", line 50, in <module>
    dataloader = DataLoader(dataset, batch_size=None, shuffle=False)
  File "/fsx/users/binhtang/conda/envs/torchdata/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 232, in __init__
    torch.utils.data.graph_settings.apply_shuffle_settings(dataset, shuffle=shuffle)
  File "/fsx/users/binhtang/conda/envs/torchdata/lib/python3.9/site-packages/torch/utils/data/graph_settings.py", line 31, in apply_shuffle_settings
    graph = torch.utils.data.graph.traverse(datapipe)
  File "/fsx/users/binhtang/conda/envs/torchdata/lib/python3.9/site-packages/torch/utils/data/graph.py", line 64, in traverse
    d[datapipe].update(traverse(item, exclude_primitive))
  File "/fsx/users/binhtang/conda/envs/torchdata/lib/python3.9/site-packages/torch/utils/data/graph.py", line 64, in traverse
    d[datapipe].update(traverse(item, exclude_primitive))
  File "/fsx/users/binhtang/conda/envs/torchdata/lib/python3.9/site-packages/torch/utils/data/graph.py", line 64, in traverse
    d[datapipe].update(traverse(item, exclude_primitive))
  [Previous line repeated 979 more times]
  File "/fsx/users/binhtang/conda/envs/torchdata/lib/python3.9/site-packages/torch/utils/data/graph.py", line 61, in traverse
    items = list_connected_datapipes(datapipe, exclude_primitive)
  File "/fsx/users/binhtang/conda/envs/torchdata/lib/python3.9/site-packages/torch/utils/data/graph.py", line 47, in list_connected_datapipes
    p.dump(scan_obj)
  File "/fsx/users/binhtang/conda/envs/torchdata/lib/python3.9/site-packages/torch/utils/data/_typing.py", line 344, in __hash__
    return hash((self.__name__, self.type))
  File "/fsx/users/binhtang/conda/envs/torchdata/lib/python3.9/site-packages/torch/utils/data/_typing.py", line 235, in __hash__
    return hash(self.param)
  File "/fsx/users/binhtang/conda/envs/torchdata/lib/python3.9/typing.py", line 752, in __hash__
    return hash((self.__origin__, self.__args__))
RecursionError: maximum recursion depth exceeded while calling a Python object
```

### Versions

```
PyTorch version: 1.11.0.dev20211223+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.20.4
Libc version: glibc-2.27

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-1051-aws-x86_64-with-glibc2.27
Is CUDA available: False
CUDA runtime version: 11.1.105
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] torch==1.11.0.dev20211223+cpu
[pip3] torchdata==0.3.0a0+25530cf
[pip3] torchtext==0.12.0a0+2683aa8
[conda] numpy                     1.21.5                   pypi_0    pypi
[conda] torch                     1.11.0.dev20211223+cpu          pypi_0    pypi
[conda] torchdata                 0.3.0a0+25530cf           dev_0    <develop>
[conda] torchtext                 0.12.0a0+2683aa8          pypi_0    pypi
```

**Comment by ejguan** [comment]
Thanks for pointing out the issue.

@NivekT We should add test cases of using Datapipe inside DataLoader to prevent such case happening again.
