### ISSUE TITLE
Certain DataPipes may not work with DataLoader multiprocessing if `dill` is installed

### ISSUE THREAD

**Issue by NivekT** [pytorch/data#214]
### 🐛 Describe the bug

The following code snippet doesn't work on MacOS when the package `dill` is installed.

```python
import numpy as np
from torch.utils.data import DataLoader
import torchdata.datapipes as dp

def row_processer(row):
    return {"label": np.array(row[0], np.int32), "data": np.array(row[1:], dtype=np.float64)}

if __name__ == '__main__':
    datapipe = dp.iter.IterableWrapper([[1, 2, 3, 4], [1, 2, 3, 4]])
    datapipe = datapipe.map(row_processer)
    dl = DataLoader(dataset=datapipe, batch_size=50, shuffle=True, num_workers=2)  # Works when num_workers=0
    first = next(iter(dl))
    labels, features = first['label'], first['data']
```
#### Error Message:
```
Traceback (most recent call last):
  File "/Users/ktse/scratch/___.py", line 45, in <module>
    first = next(iter(dl))
  File "/Users/ktse/pytorch/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/Users/ktse/pytorch/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/Users/ktse/pytorch/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/Users/ktse/pytorch/torch/_utils.py", line 457, in reraise
    raise exception
NameError: Caught NameError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/Users/ktse/pytorch/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/Users/ktse/pytorch/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/Users/ktse/pytorch/torch/utils/data/_typing.py", line 365, in wrap_generator
    response = gen.send(None)
  File "/Users/ktse/pytorch/torch/utils/data/datapipes/iter/callable.py", line 99, in __iter__
    yield self._apply_fn(data)
  File "/Users/ktse/pytorch/torch/utils/data/datapipes/iter/callable.py", line 64, in _apply_fn
    return self.fn(data)
  File "/Users/ktse/scratch/___.py", line 39, in row_processer
    return {"label": np.array(row[0], np.int32), "data": np.array(row[1:], dtype=np.float64)}
NameError: name 'np' is not defined
```

### Versions

OS: macOS 12.1 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0
CMake version: version 3.19.6
Libc version: N/A

Python version: 3.9.6 (default, Aug 18 2021, 12:38:10)  [Clang 10.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torchdata==1.0.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.3.0           hecd8cb5_517  
[conda] mkl-include               2021.3.0           hecd8cb5_517  
[conda] mkl-service               2.4.0            py39h9ed2024_0  
[conda] mkl_fft                   1.3.0            py39h4a7008c_2  
[conda] mkl_random                1.2.2            py39hb2f4e1b_0  
[conda] numpy                     1.20.3           py39h4b4dc7a_0  
[conda] numpy-base                1.20.3           py39he0bd621_0
[conda] dill                      0.3.4              pyhd3eb1b0_0  

#### Workarounds:
1. Putting the import statement right before its usage
2. Uninstall `dill`
3. Set `num_workers=0`

cc: @VitalyFedyunin @ejguan  @NivekT

**Comment by NivekT** [comment]
Update on what we are going to do about this:
1. Opened an issue with `dill`
2. Change our implementation:
    - Try `pickle` first, if it fails (most likely because the function is a lambda), use `dill` with `recurse=True`
    - Also store the state: whether we use `pickle` or `dill` while serializing

We should be careful to see if `recurse=True` has any unreasonable side effect.

**Comment by NivekT** [comment]
This is fixed as https://github.com/pytorch/pytorch/pull/72896 has landed.
