### ISSUE TITLE
Exception: Could not get the file at https://s3.amazonaws.com/... [RequestException] None.

### ISSUE THREAD

**Issue by PatternFinder** [pytorch/data#355]
### 🐛 Describe the bug

Code that throw the excpetion:
>>>from torchtext.datasets import WikiText2
>>>train_iter, val_iter, test_iter = WikiText2()

code refuse to download via torchtext.datasets, but I can download the data right off the browser just fine.

Exception raised:
Traceback (most recent call last):
  File "C:\python\Python310\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\python\Python310\lib\site-packages\urllib3\connectionpool.py", line 994, in _prepare_proxy  
    conn.connect()
  File "C:\python\Python310\lib\site-packages\urllib3\connection.py", line 364, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "C:\python\Python310\lib\site-packages\urllib3\connection.py", line 499, in _connect_tls_proxy  
    socket = ssl_wrap_socket(
  File "C:\python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket      
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\python\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\python\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\python\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python\Python310\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\python\Python310\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\python\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /research.metamind.io/wikitext/wikitext-2-v1.zip (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python\Python310\lib\site-packages\torchdata\datapipes\iter\load\online.py", line 17, in _get_response_from_http
    r = session.get(url, stream=True)
  File "C:\python\Python310\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "C:\python\Python310\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\python\Python310\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\python\Python310\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /research.metamind.io/wikitext/wikitext-2-v1.zip (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python\my\1. pytorch\language_modeling_transf.py", line 83, in <module>
    vocab = build_vocab_from_iterator(map(tokenizer, train_iter), specials=['<unk>'])
  File "C:\python\Python310\lib\site-packages\torchtext\vocab\vocab_factory.py", line 92, in build_vocab_from_iterator
    for tokens in iterator:
  File "C:\python\Python310\lib\site-packages\torch\utils\data\_typing.py", line 366, in wrap_generator
    response = gen.send(None)
  File "C:\python\Python310\lib\site-packages\torchdata\datapipes\iter\util\plain_text_reader.py", line 116, in __iter__
    for path, file in self.source_datapipe:
  File "C:\python\Python310\lib\site-packages\torch\utils\data\_typing.py", line 366, in wrap_generator
    response = gen.send(None)
  File "C:\python\Python310\lib\site-packages\torch\utils\data\datapipes\iter\fileopener.py", line 60, in __iter__
    yield from get_file_binaries_from_pathnames(self.datapipe, self.mode, self.encoding)
  File "C:\python\Python310\lib\site-packages\torch\utils\data\datapipes\utils\common.py", line 85, in get_file_binaries_from_pathnames
    for pathname in pathnames:
  File "C:\python\Python310\lib\site-packages\torch\utils\data\_typing.py", line 366, in wrap_generator
    response = gen.send(None)
  File "C:\python\Python310\lib\site-packages\torch\utils\data\datapipes\iter\combining.py", line 46, in __iter__
    for data in dp:
  File "C:\python\Python310\lib\site-packages\torch\utils\data\_typing.py", line 366, in wrap_generator
    response = gen.send(None)
  File "C:\python\Python310\lib\site-packages\torch\utils\data\datapipes\iter\filelister.py", line 51, in __iter__
    for path in self.datapipe:
  File "C:\python\Python310\lib\site-packages\torch\utils\data\_typing.py", line 366, in wrap_generator
    response = gen.send(None)
  File "C:\python\Python310\lib\site-packages\torch\utils\data\datapipes\iter\grouping.py", line 140, in __iter__
    for element in self.datapipe:
  File "C:\python\Python310\lib\site-packages\torch\utils\data\_typing.py", line 366, in wrap_generator
    response = gen.send(None)
  File "C:\python\Python310\lib\site-packages\torch\utils\data\datapipes\iter\callable.py", line 112, in __iter__
    for data in self.datapipe:
  File "C:\python\Python310\lib\site-packages\torch\utils\data\_typing.py", line 356, in __next__
    return next(self.iterator)
  File "C:\python\Python310\lib\site-packages\torch\utils\data\datapipes\iter\combining.py", line 190, in get_generator_by_instance
    yield from self.main_datapipe.get_next_element_by_instance(self.instance_id)
  File "C:\python\Python310\lib\site-packages\torch\utils\data\datapipes\iter\combining.py", line 301, in get_next_element_by_instance
    yield self._find_next(instance_id)
  File "C:\python\Python310\lib\site-packages\torch\utils\data\datapipes\iter\combining.py", line 275, in _find_next
    value = next(self._datapipe_iterator)
  File "C:\python\Python310\lib\site-packages\torch\utils\data\_typing.py", line 366, in wrap_generator
    response = gen.send(None)
  File "C:\python\Python310\lib\site-packages\torch\utils\data\datapipes\iter\combining.py", line 46, in __iter__
    for data in dp:
  File "C:\python\Python310\lib\site-packages\torch\utils\data\_typing.py", line 366, in wrap_generator
    response = gen.send(None)
  File "C:\python\Python310\lib\site-packages\torchdata\datapipes\iter\util\saver.py", line 48, in __iter__
    for filepath, data in self.source_datapipe:
  File "C:\python\Python310\lib\site-packages\torch\utils\data\_typing.py", line 366, in wrap_generator
    response = gen.send(None)
  File "C:\python\Python310\lib\site-packages\torchdata\datapipes\iter\util\hashchecker.py", line 62, in __iter__
    for file_name, data in self.source_datapipe:
  File "C:\python\Python310\lib\site-packages\torch\utils\data\_typing.py", line 366, in wrap_generator
    response = gen.send(None)
  File "C:\python\Python310\lib\site-packages\torch\utils\data\datapipes\iter\callable.py", line 112, in __iter__
    for data in self.datapipe:
  File "C:\python\Python310\lib\site-packages\torch\utils\data\_typing.py", line 366, in wrap_generator
    response = gen.send(None)
  File "C:\python\Python310\lib\site-packages\torch\utils\data\datapipes\iter\callable.py", line 112, in __iter__
    for data in self.datapipe:
  File "C:\python\Python310\lib\site-packages\torch\utils\data\_typing.py", line 366, in wrap_generator
    response = gen.send(None)
  File "C:\python\Python310\lib\site-packages\torchdata\datapipes\iter\load\online.py", line 56, in __iter__
    yield _get_response_from_http(url, timeout=self.timeout)
  File "C:\python\Python310\lib\site-packages\torchdata\datapipes\iter\load\online.py", line 24, in _get_response_from_http
    raise Exception(f"Could not get the file at {url}. [RequestException] {e.response}.")
Exception: Could not get the file at https://s3.amazonaws.com/research.metamind.io/wikitext/wikitext-2-v1.zip. [RequestException] None.

### Versions

PyTorch version: 1.11.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19044
Is CUDA available: True
CUDA runtime version: 11.3.58
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060 Ti
Nvidia driver version: 512.15
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.11.0+cu113
[pip3] torchaudio==0.11.0+cu113
[pip3] torchdata==0.3.0
[pip3] torchtext==0.12.0
[pip3] torchvision==0.12.0+cu113
[conda] Could not collect

**Comment by PatternFinder** [comment]
Alternatively, how could I change wikitext2.py so I can point it to a locally saved copy, as a circumvention, thanks!

**Comment by PatternFinder** [comment]
> Can you please try to run the following code to see if it works:
> 
> ```python
> import requests
> 
> with requests.Session() as session:
>     r = session.get("https://s3.amazonaws.com/research.metamind.io/wikitext/wikitext-2-v1.zip", timeout=None, stream=True)
> ```

That thrown the following:


Traceback (most recent call last):
  File "C:\python\Python310\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\python\Python310\lib\site-packages\urllib3\connectionpool.py", line 994, in _prepare_proxy
    conn.connect()
  File "C:\python\Python310\lib\site-packages\urllib3\connection.py", line 364, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "C:\python\Python310\lib\site-packages\urllib3\connection.py", line 499, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "C:\python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\python\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\python\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\python\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python\Python310\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\python\Python310\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\python\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /research.metamind.io/wikitext/wikitext-2-v1.zip (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python\my\pytorch\download test.py", line 4, in <module>
    r = session.get("https://s3.amazonaws.com/research.metamind.io/wikitext/wikitext-2-v1.zip", timeout=None, stream=True)
  File "C:\python\Python310\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "C:\python\Python310\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\python\Python310\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\python\Python310\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /research.metamind.io/wikitext/wikitext-2-v1.zip (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

**Comment by ejguan** [comment]
Can you check your `ssl` version?
```py
import ssl
print(ssl.OPENSSL_VERSION)
```

**Comment by PatternFinder** [comment]
> 



> Can you check your `ssl` version?
> 
> ```python
> import ssl
> print(ssl.OPENSSL_VERSION)
> ```

OpenSSL 1.1.1n  15 Mar 2022

**Comment by ejguan** [comment]
> OpenSSL 1.1.1n 15 Mar 2022

Thanks for confirming. Then, your SSL should be fine. Now, let's see whether or not your network admin prevents you to download.

Does it work if you add `verify=False` to the code above within `session.get(..., verify=False)`?

**Comment by PatternFinder** [comment]
> verify=False

think we're onto something here...
for verify=False, we get:

requests.exceptions.ProxyError: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /research.metamind.io/wikitext/wikitext-2-v1.zip (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))

I can still grab the file just copying the URL into chrome fine

**Comment by ejguan** [comment]
What is the result of `urllib.request.getproxies()`?

It seems related to a bug in Python that the proxy used for Windows is incorrect. https://bugs.python.org/issue42627

**Comment by ejguan** [comment]
And, what's the version of your `urllib3`?

**Comment by ejguan** [comment]
@PatternFinder Any update?

**Comment by PatternFinder** [comment]
> What is the result of `urllib.request.getproxies()`?
> 
> It seems related to a bug in Python that the proxy used for Windows is incorrect. https://bugs.python.org/issue42627

thanks for following up.
getproxies() returns:
{'http': 'http://127.0.0.1:3213', 'https': 'https://127.0.0.1:3213'}

**Comment by PatternFinder** [comment]
> @PatternFinder Any update?



> And, what's the version of your `urllib3`?

Name: urllib3
Version: 1.26.9

**Comment by ejguan** [comment]
I see. This is actually a bug from python library. Just to verify it, does it work if you run the following code:
```
import requests
import urllib

proxies = urllib.request.getproxies()
proxies['https'] = "http" + proxies['https'][5:]

with requests.Session() as session:
    r = session.get("https://s3.amazonaws.com/research.metamind.io/wikitext/wikitext-2-v1.zip", timeout=None, stream=True, proxies=proxies)
```

If this works, we can add a quick fix to TorchData to override origin Python behavior and wait until Python add a patch to fix it.

**Comment by PatternFinder** [comment]
> I see. This is actually a bug from python library. Just to verify it, does it work if you run the following code:
> 
> ```python
> import requests
> import urllib
> 
> proxies = urllib.request.getproxies()
> proxies['https'] = "http" + proxies['https'][5:]
> 
> with requests.Session() as session:
>     r = session.get("https://s3.amazonaws.com/research.metamind.io/wikitext/wikitext-2-v1.zip", timeout=None, stream=True, proxies=proxies)
> ```
> 
> If this works, we can add a quick fix to TorchData to override origin Python behavior and wait until Python add a patch to fix it.

Ok this works, replacing the proxy 'https' with 'http" will give a 200. 

However I still get an error with torchtext.datasets, could you help me out with this? thanks:

from torchtext.datasets import WikiText2    
train_iter, val_iter, test_iter = WikiText2(root='D:/ML/datasets/') # this makes a directory named 'WikiText2', but it's empty
for i in train_iter: # this throws the error Exception has occurred: Exception
# Could not get the file at https://s3.amazonaws.com/research.metamind.io/wikitext/wikitext-2-v1.zip. [RequestException] None.
    print(i)
    break

**Comment by ejguan** [comment]
> Ok this works, replacing the proxy 'https' with 'http" will give a 200.

I can send a patch to TorchData later today. When it's landed, you can use nightly TorchText to support such behavior.

**Comment by ejguan** [comment]
@PatternFinder #371 is landed yesterday and the nightly release of TorchData has been updated. Could you please try to install `torchtext` and `torchdata` via `pip3 install --pre torch torchdata torchtext --extra-index-url https://download.pytorch.org/whl/nightly/cpu`?
