### ISSUE TITLE
TarArchiveReader is not functioning with HTTPReader or GDriveReader

### ISSUE THREAD

**Issue by NivekT** [pytorch/data#42]
This issue was discovered as part of #40. The `TarArchiveReader` implementation is likely wrong:

1. An error is raised when we attempt to use `TarArchiveReader` immediately after `HTTPReader` because the HTTP stream does not support the operation `seek`:

```
file_url = "http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz"
http_reader_dp = HttpReader(IterableWrapper([file_url]))
tar_dp = http_reader_dp.read_from_tar()
for fname, stream in tar_dp:
    print(f"{fname}: {stream.read()}")
```
It returns an error that looks something like this:
```
Traceback (most recent call last):
  File "/Users/ktse/data/test/test_stream.py", line 66, in <module>
    for fname, stream in tar_dp:
  File "/Users/.../data/torchdata/datapipes/iter/util/tararchivereader.py", line 62, in __iter__
    raise e
  File "/Users/.../data/torchdata/datapipes/iter/util/tararchivereader.py", line 48, in __iter__
    tar = tarfile.open(fileobj=cast(Optional[IO[bytes]], data_stream), mode=self.mode)
  File "/Users/.../miniconda3/envs/pytorch/lib/python3.9/tarfile.py", line 1609, in open
    saved_pos = fileobj.tell()
io.UnsupportedOperation: seek
```
Currently, you can work around by downloading the file in advance (or caching it with `OnDiskCacheHolderIterDataPipe`). In those cases, `TarArchiveReader` works as intended.

2. `TarArchiveReader` also doesn't work with `GDriveReader` because of the return type

```
amazon_review_url = "https://drive.google.com/uc?export=download&id=0Bz8a_Dbh9QhbaW12WVVZS2drcnM"
gdrive_reader_dp = OnlineReader(IterableWrapper([amazon_review_url]))
tar_dp = gdrive_reader_dp.read_from_tar()
```
This is because `validate_pathname_binary_tuple` requires `BufferedIOBase`. Perhaps it should accept HTTP response as well?

https://github.com/pytorch/data/blob/85d8bbe235cd58f270c17367a5577de107b0095f/torchdata/datapipes/utils/common.py#L66-L76
```
test/test_stream.py:None (test/test_stream.py)
test_stream.py:79: in <module>
    for fname, stream in tar_dp:
../torchdata/datapipes/iter/util/tararchivereader.py:43: in __iter__
    validate_pathname_binary_tuple(data)
../torchdata/datapipes/utils/common.py:74: in validate_pathname_binary_tuple
    raise TypeError(
E   TypeError: pathname binary tuple should have BufferedIOBase based binary type, but got <class 'urllib3.response.HTTPResponse'>
```

cc @VitalyFedyunin @ejguan

**Comment by ejguan** [comment]
> An error is raised when we attempt to use TarArchiveReader immediately after HTTPReader because the HTTP stream does not support the operation seek:

Correct me if I am wrong, `tarfile` doesn't work with `HTTPResponse`.

If so, the second problem is not a problem. Even if we change the `validate_pathname_...` to accept `HTTPResponse`, `tarfile` is not able to open it for `GDriveReader`

**Comment by NivekT** [comment]
> > An error is raised when we attempt to use TarArchiveReader immediately after HTTPReader because the HTTP stream does not support the operation seek:
> 
> Correct me if I am wrong, `tarfile` doesn't work with `HTTPResponse`.
> 
> If so, the second problem is not a problem. Even if we change the `validate_pathname_...` to accept `HTTPResponse`, `tarfile` is not able to open it for `GDriveReader`

Based on my observation, `tarfile.open` seems to handle `HTTPResponse` fine. Definitely a bit surprising.

The code snippet below runs:
```
for fname, stream in gdrive_reader_dp: #in tar_dp:
    tar = tarfile.open(fileobj=cast(Optional[IO[bytes]], stream), mode="r:*")
    for tarinfo in tar:
        if not tarinfo.isfile():
            continue
        extracted_fobj = tar.extractfile(tarinfo)
        print(tarinfo.name, extracted_fobj)  # type: ignore[misc]
        if "readme" in tarinfo.name:
            print(extracted_fobj.read())
```
Returns:
```
amazon_review_polarity_csv/test.csv <ExFileObject name=''>
amazon_review_polarity_csv/train.csv <ExFileObject name=''>
amazon_review_polarity_csv/readme.txt <ExFileObject name=''>
b'Amazon Review Polaridy Dataset\n\nVersion 3, Updated 09/09/2015\n\nORIGIN\n\nThe Amazon reviews dataset consists of reviews from amazon. The data span a period of 18 years, including ~35 million reviews up to March 2013. Reviews include product and user information, ratings, and a plaintext review. For more information, please refer to the following paper: J. McAuley and J. Leskovec. Hidden factors and hidden topics: understanding rating dimensions with review text. RecSys, 2013.\n\nThe Amazon reviews polarity dataset is constructed by Xiang Zhang (xiang.zhang@nyu.edu) from the above dataset. It is used as a text classification benchmark in the following paper: Xiang Zhang, Junbo Zhao, Yann LeCun. Character-level Convolutional Networks for Text Classification. Advances in Neural Information Processing Systems 28 (NIPS 2015).\n\n\nDESCRIPTION\n\nThe Amazon reviews polarity dataset is constructed by taking review score 1 and 2 as negative, and 4 and 5 as positive. Samples of score 3 is ignored. In the dataset, class 1 is the negative and class 2 is the positive. Each class has 1,800,000 training samples and 200,000 testing samples.\n\nThe files train.csv and test.csv contain all the training samples as comma-sparated values. There are 3 columns in them, corresponding to class index (1 or 2), review title and review text. The review title and text are escaped using double quotes ("), and any internal double quote is escaped by 2 double quotes (""). New lines are escaped by a backslash followed with an "n" character, that is "\\n".\n'
```

I omitted printing out `test.csv` and `train.csv` but their contents seem valid.

It will be interesting to see how `Zip` and `XZ` readers do with `HTTPResponse`. I suspect it may not work for those.
One better option is probably to have `TarArchiveReader` explicitly handle `HTTPResponse`, but for now I think it should be okay to require users to download or cache the files first. What do you think?

**Comment by ejguan** [comment]
So, if it's working for `GDriveReader`, then the problem probably come from `def _get_response_from_http`.

> See also The Requests package is recommended for a higher-level HTTP client interface.
Based on the Python doc, do you want to try `requests` rather than `urllib` to get respond?

**Comment by NivekT** [comment]
> So, if it's working for `GDriveReader`, then the problem probably come from `def _get_response_from_http`.
> 
> > See also The Requests package is recommended for a higher-level HTTP client interface.
> 
> Based on the Python doc, do you want to try `requests` rather than `urllib` to get respond?

Switching to use the module `requests` still returns an error:
```
Traceback (most recent call last):
  File "/Users/ktse/data/test/temp.py", line 27, in <module>
    tar = tarfile.open(fileobj=cast(Optional[IO[bytes]], stream), mode="r:*")
  File "/Users/ktse/miniconda3/envs/pytorch/lib/python3.9/tarfile.py", line 1609, in open
    saved_pos = fileobj.tell()
AttributeError: 'Response' object has no attribute 'tell'
```
However, we can access its content and covert it into `BytesIO`:

```
# tar = tarfile.open(fileobj=cast(Optional[IO[bytes]], stream), mode="r:*")  # Original method
tar = tarfile.open(fileobj=cast(Optional[IO[bytes]], io.BytesIO(stream.data)), mode="r:*") # This works
```

I am leaning towards adding an option to `TarArchiveReader` (and other readers as needed) to allow them to handle HTTP response. Does that sound about right?

Full runnable code snippet:
```
file_url = "http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz"
http_reader_dp = HttpReader(IterableWrapper([file_url]))
# tar_dp = http_reader_dp.read_from_tar()

for fname, stream in http_reader_dp: #in tar_dp:
    print()
    print(type(stream))
    # tar = tarfile.open(fileobj=cast(Optional[IO[bytes]], stream), mode="r:*")  # Original way
    tar = tarfile.open(fileobj=cast(Optional[IO[bytes]], io.BytesIO(stream.data)), mode="r:*") # This works
    for tarinfo in tar:
        if not tarinfo.isfile():
            continue
        extracted_fobj = tar.extractfile(tarinfo)
        print(tarinfo.name, extracted_fobj)  # type: ignore[misc]
        if "readme" in tarinfo.name:
            print(extracted_fobj.read())
```

**Comment by ejguan** [comment]
Looking at https://2.python-requests.org/en/master/user/advanced/#body-content-workflow. We should be able to do it as:
```py
file_url = "http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz"
r = requests.open(file_url, stream=True)
r = r.raw  # Get the HTTPResponse
tar = tarfile.open(fileobj=r, mode="r:*")
```
