### ISSUE TITLE
RuntimeError: Socket Timeout when rank 0 arrives late

### ISSUE THREAD

**Issue by mreso** [pytorch/data#659]
### 🐛 Describe the bug

Hi,

I am getting a RuntimeError: Socket Timeout when using a datapipe with the legacy DataLoader and rank 0 arrives significantly later (6+ secs) than other ranks. In my case the late arrival was due to loading some data through http and it showed only when scaling past 4 workers.

The full stack trace is:

``` E       torch.multiprocessing.spawn.ProcessRaisedException:
E
E       -- Process 5 terminated with the following error:
E       Traceback (most recent call last):
E         File "/mreso/conda/envs/datapipe/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
E           fn(i, *args)
E         File "/mreso/test_timeout_repro.py", line 20, in training
E           item = next(iter(dl))
E         File "/mreso/conda/envs/datapipe/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 443, in __iter__
E           return self._get_iterator()
E         File "/mreso/conda/envs/datapipe/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 389, in _get_iterator
E           return _MultiProcessingDataLoaderIter(self)
E         File "/mreso/conda/envs/datapipe/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1023, in __init__
E           super(_MultiProcessingDataLoaderIter, self).__init__(loader)
E         File "/mreso/conda/envs/datapipe/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 610, in __init__
E           self._shared_seed = loader._get_shared_seed()
E         File "/mreso/conda/envs/datapipe/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 590, in _get_shared_seed
E           store.wait([_utils.DATAPIPE_SHARED_SEED], _utils.MP_STATUS_CHECK_INTERVAL)
E       RuntimeError: Socket Timeout
```

I've create a minimal example that fails for 2 workers as well as for 8 workers. I only get the error when rank 0 takes longer. For rank > 0 it seems to be fine. You can run the script with pytest.

```python
import os
import pytest
import time

import torch
from torchdata.datapipes.iter import IterDataPipe

class FooLister(IterDataPipe):
    def __iter__(self):
        for x in range(10):
            yield x

def training(rank, world_size, late_rank):
    pg = torch.distributed.init_process_group("gloo", rank=rank, world_size=world_size)

    # simulate data loading (when rank 0 arrives last test fails)
    time.sleep(6 if rank == late_rank else 0)
    
    dp = FooLister()
    dp = dp.shuffle().sharding_filter()

    dl = torch.utils.data.DataLoader(dp, num_workers=2)
    item = next(iter(dl))

@pytest.mark.parametrize(["world_size", "late_rank"], [(2,0), (8,0), (2,1), (8,7)])
def test_web_datapipe(world_size, late_rank):
    os.environ["MASTER_ADDR"] = "localhost"
    os.environ["MASTER_PORT"] = "29500"

    torch.multiprocessing.spawn(
        training,
        args=(world_size, late_rank),
        nprocs=world_size,
        join=True,
    )
```

### Versions

Environment:
```
Collecting environment information...
PyTorch version: 1.13.0.dev20220713+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.20.4
Libc version: glibc-2.27

Python version: 3.9.12 (main, Jun  1 2022, 11:38:51)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-1051-aws-x86_64-with-glibc2.27
Is CUDA available: False
CUDA runtime version: 11.1.105
GPU models and configuration: No devices found.
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.1
[pip3] torch==1.13.0.dev20220713+cu116
[pip3] torchaudio==0.13.0.dev20220713+cu116
[pip3] torchdata==0.5.0.dev20220713
[pip3] torchvision==0.14.0.dev20220713+cu116
[conda] numpy                     1.23.1                   pypi_0    pypi
[conda] torch                     1.13.0.dev20220713+cu116          pypi_0    pypi
[conda] torchaudio                0.13.0.dev20220713+cu116          pypi_0    pypi
[conda] torchdata                 0.5.0.dev20220713          pypi_0    pypi
[conda] torchvision               0.14.0.dev20220713+cu116          pypi_0    pypi
```

**Comment by VitalyFedyunin** [comment]
CC @ejguan
